# Generated by Django 3.1.5 on 2021-01-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posttopic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='send_command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trxid', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=20)),
                ('message', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
